from __future__ import annotations

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.database import get_db
from app.simulation.engine import simulate_scenario
from app.simulation.ssh import simulate_ssh_brute_force
from app.simulation.portscan import simulate_port_scan
from app.simulation.auth import simulate_suspicious_auth
from app.simulation.network_utility import simulate_network_utility
from app.simulation.multistage import simulate_multi_stage_attack
from app.simulation.pipeline import normalize_simulation_events

from app.api.telemetry import ingest_event


router = APIRouter(
    prefix="/api/simulation",
    tags=["Attack Simulation"],
)


def generate_scenario_events(
    scenario: str,
    source_ip: str,
    target_ip: str,
    username: str,
) -> dict:
    scenario = scenario.upper().strip()

    if scenario == "SSH_BRUTE_FORCE":
        return simulate_ssh_brute_force(
            source_ip=source_ip,
            target_ip=target_ip,
            username=username,
            attempts=8,
        )

    if scenario == "PORT_SCAN":
        return simulate_port_scan(
            source_ip=source_ip,
            target_ip=target_ip,
        )

    if scenario == "SUSPICIOUS_AUTH":
        return simulate_suspicious_auth(
            source_ip=source_ip,
            target_ip=target_ip,
            username=username,
            failed_attempts=5,
        )

    if scenario == "SUSPICIOUS_NETWORK_UTILITY":
        return simulate_network_utility(
            source_ip=source_ip,
            target_ip=target_ip,
        )

    if scenario == "MULTI_STAGE_ATTACK":
        return simulate_multi_stage_attack(
            source_ip=source_ip,
            target_ip=target_ip,
            username=username,
        )

    return {
        "status": "SIMULATION_REJECTED",
        "mode": "LAB",
        "simulation_only": True,
        "reason": f"Unsupported scenario: {scenario}",
    }


@router.post("/pipeline")
async def simulation_detection_pipeline(
    scenario: str,
    source_ip: str = "192.168.56.220",
    target_ip: str = "192.168.56.10",
    username: str = "lab-user",
    db: AsyncSession = Depends(get_db),
):
    """
    Run a LAB-only attack simulation through the
    existing telemetry and detection pipeline.

    No real attack traffic is generated.
    """

    scenario = scenario.upper().strip()

    allowed = {
        "SSH_BRUTE_FORCE",
        "PORT_SCAN",
        "SUSPICIOUS_AUTH",
        "SUSPICIOUS_NETWORK_UTILITY",
        "MULTI_STAGE_ATTACK",
    }

    if scenario not in allowed:
        return {
            "status": "SIMULATION_REJECTED",
            "mode": "LAB",
            "simulation_only": True,
            "real_attack": False,
            "reason": "Unsupported simulation scenario.",
            "scenario": scenario,
        }

    simulation = generate_scenario_events(
        scenario=scenario,
        source_ip=source_ip,
        target_ip=target_ip,
        username=username,
    )

    if simulation.get("status") == "SIMULATION_REJECTED":
        return simulation

    # ---------------------------------------------------------
    # Flatten events from single-stage or multi-stage scenario
    # ---------------------------------------------------------

    raw_events = []

    if scenario == "MULTI_STAGE_ATTACK":
        for stage in simulation.get("stages", []):
            raw_events.extend(
                stage.get("events", [])
            )
    else:
        raw_events = simulation.get(
            "events",
            [],
        )

    normalized_events = normalize_simulation_events(
        raw_events
    )

    # ---------------------------------------------------------
    # Feed every normalized event through the EXISTING
    # telemetry ingestion endpoint/function.
    # ---------------------------------------------------------

    pipeline_results = []

    for event in normalized_events:
        result = await ingest_event(
            event=event,
            db=db,
        )

        pipeline_results.append(
            {
                "event_type": event.get("event_type"),
                "source_ip": event.get("source_ip"),
                "result": result,
            }
        )

    # ---------------------------------------------------------
    # Collect detections and incidents generated by pipeline
    # ---------------------------------------------------------

    detection_ids = set()
    detection_names = set()
    incident_ids = set()

    for item in pipeline_results:
        result = item.get("result", {})

        for detection in result.get(
            "detections",
            [],
        ):
            detection_id = detection.get("id")

            if detection_id is not None:
                detection_ids.add(
                    detection_id
                )

            name = detection.get(
                "detection_name"
            )

            if name:
                detection_names.add(name)

        for incident in result.get(
            "correlated_incidents",
            [],
        ):
            incident_id = incident.get(
                "incident_id"
            )

            if incident_id is not None:
                incident_ids.add(
                    incident_id
                )

    return {
        "status": "SIMULATION_PIPELINE_COMPLETE",
        "mode": "LAB",
        "simulation_only": True,
        "real_attack": False,
        "scenario": scenario,
        "source_ip": source_ip,
        "target_ip": target_ip,
        "events_generated": len(raw_events),
        "events_ingested": len(normalized_events),
        "detections_generated": len(
            detection_ids
        ),
        "detection_ids": detection_ids,
        "detection_names": sorted(
            detection_names
        ),
        "incident_ids": sorted(
            incident_ids
        ),
        "pipeline": [
            "SIMULATION",
            "NORMALIZATION",
            "TELEMETRY",
            "SECURITY_EVENT",
            "DETECTION_RULES",
            "THRESHOLD",
            "DEDUPLICATION",
            "CORRELATION",
            "INCIDENT",
        ],
    }
